name: Generate Snake

on:
  schedule:
    - cron: "0 17 * * 6"   # Chủ nhật 00:00 giờ Việt Nam (UTC+7)
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: an0other
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=FF6B6B&color_dots=#ebedf0,#c6e48b,#7bc96f,#239a3b,#196127
            dist/github-contribution-grid-snake-dark.svg?color_snake=00E5FF&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          force_orphan: true
