name: Generate Snake

on:
  schedule:
    - cron: "0 17 * * 6"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: an0other
          outputs: |
            # Bản sáng: Dải màu xanh lá cây Pastel (dịu mắt, không bị rực)
            dist/github-contribution-grid-snake.svg?color_snake=#1da1f2&color_dots=#f0f2f5,#c6e48b,#7bc96f,#239a3b,#196127
            # Bản tối: Dải màu Xám xanh hiện đại (kiểu giao diện VS Code)
            dist/github-contribution-grid-snake-dark.svg?color_snake=#e99149&color_dots=#161b22,#2d333b,#404c5a,#768390,#adbac7

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          force_orphan: true
